name: Deploy to Web server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build ReadTheVoice
      run: npm install && npm run build

    - name: Uploading to the Web server
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        local-dir: ./dist/
        server-dir: ${{ secrets.ftp_dir }}
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}